site_name: Build Server
site_description: A CI/CD system for building programs
site_author: Larry Banks

repo_url: https://github.com/larryb02/Build-Server
repo_name: larryb02/Build-Server

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition:
  - pymdownx.details:

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API: api.md
