---
- name: Deploy buildserver-runner
  kubernetes.core.k8s:
    state: "{{ k8s_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: buildserver-runner
        namespace: "{{ cluster_namespace }}"
        labels:
          app: buildserver-runner
      spec:
        replicas: "{{ runner_replicas }}"
        selector:
          matchLabels:
            app: buildserver-runner
        template:
          metadata:
            labels:
              app: buildserver-runner
          spec:
            containers:
              - name: buildserver-runner
                image: "{{ runner_image }}"
                imagePullPolicy: "{{ image_pull_policy }}"
                env:
                  - name: APISERVER_HOST
                    value: "{{ apiserver_host }}"
                  - name: LOG_LEVEL
                    value: DEBUG
                envFrom:
                  - configMapRef:
                      name: buildserver-config
                  - secretRef:
                      name: buildserver-secrets
