---
- name: Deploy Build Server to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - common
    - postgres
    - rabbitmq
    - buildserver-api
    - buildserver-runner
