name: Manage bastion host

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLUSTER_DIR: infra/terraform/aws/bastion

jobs:
  create_bastion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - run: |
        terraform -chdir=$CLUSTER_DIR init
        terraform -chdir=$CLUSTER_DIR validate
        terraform -chdir=$CLUSTER_DIR apply -auto-approve

  bootstrap_bastion:
    runs-on: ubuntu-latest
    needs: [create_bastion]
    steps:
      - run: echo 'running ansible playbook here'
