name: Manage k3s cluster

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLUSTER_DIR: infra/terraform/aws/cluster

jobs:
  create_cluster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - run: \
        terraform -chdir=$CLUSTER_DIR init
        terraform -chdir=$CLUSTER_DIR validate
        terraform -chdir=$CLUSTER_DIR apply -auto-approve

  bootstrap_cluster:
    runs-on: ubuntu-latest
    needs: [create_cluster]
    steps:
      - run: echo 'running ansible playbook here'
