name: Tests

on:
  push:
  pull_request:
    branches: [main]

jobs:

  check-with-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: "3.12"
      - name: Install dependencies
        run: pip install pre-commit
      - name: Check with pre-commit
        run: pre-commit run --all-files
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pylint
      - name: lint
        run: pylint --exit-zero buildserver/
  #     -
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # - name: Install dependencies
      #   run: pip install -r buildserver/requirements.txt pylint pre-commit

      - name: Install dependencies
        run: pip install --no-build-isolation -e .

      # - name: Lint
      #   run: pylint --fail-under=7 buildserver/

      - name: Create env file
        run: echo "${{ secrets.DEV_ENV_FILE }}" > .env

      # - name: Add project to path
      #   run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run unit tests
        run: pytest -v buildserver/tests/unit
